# Activity 1: Introduction to Python and NumPy
## What is this?

Welcome to MATH 4242!
In these activities, we'll be exploring the material from class with hands-on computational activities.
One goal is to teach the usage of three key tools in concert with each other:

- **Python:** Python 3 is the programming language we'll be using for the semester.
Python is very versatile, and can be used in a great variety of ways for many different purposes.
Some of these purposes common today include data science and machine learning, in part motivating the decision to use it for MATH 4242.
Python is highly *extensible* meaning that in addition to the functionality offered by "base" Python, there are a great many *libraries* made by Python developers around the world which add additional features.
One of these libraries in particular will be highly relevant to us:
- **NumPy:**  NumPy (**Num**erical **Py**thon) is a Python library which adds better support for numerical computations, particularly in linear algebra.
NumPy provides the `ndarray` data type which will be our primary method of modeling matrices and vectors, as well as an extensive selection of tools for manipulating them.

- **jupyter:** Jupyter is the platform you're using right now!
Jupyter provides *notebooks,* which are the environment this is appearing in.
A notebook is comprised of *cells* which may contain *markdown* or code.
- **Markdown** is a way of encoding formatted text.
This cell is an example of markdown!

### How to use these notebooks
These activities are intended to be truly **interactive**.
Some example code will be provided, but whether in the context of an exercise or an example, you will be asked to fill many of the code cells. Especially in examples, you are invited and encouraged to discuss strategy and technique with your classmates and TA.
Crucially, you are **strongly encouraged** never to run code without at least attempting to understand what it will do (or at least, not to move on to the next thing until you have understood the previous).
Some very helpful tools are at your disposal to that end:

- You can always add an additional code cell to a notebook to experiment!
You are encouraged to do this frequently!
- You can read the documentation for various function by using the `help` function. For instance, here is how we can get more information about the `abs` function:
    ```Python
    help(abs)
    ```
    This returns:
    ```
    Help on built-in function abs in module builtins:

    abs(x, /)
        Return the absolute value of the argument.
    ```
    You can also find documentation for all NumPy functions and objects on the [NumPy website](https://numpy.org/doc/2.1/) and all Python functions and objects on the [Python website](https://docs.python.org/3/).
- Google and other search engines such as duckduckgo are your friend! When stuck, a good way to get going is to simply search "NumPy [quick description of what you are stuck with]."
Often, the most helpful results are from the [Stack Exchange](https://stackexchange.com/) family of websites.

- You are **strongly discouraged** from using generative AI to answer questions.
While Google CoLab does have generative AI features built-in, we urge you to resist its pull.
Although generative AI is fairly well-suited to the rather basic programming tasks you'll be asked to complete, **using it is only doing a disservice to yourself.**
Indeed, thinking through how to implement these algorithms and translating your knowledge from class into computerized instructions is *the point* of these activities.
Mathematics is not a spectator sport!
You will make a much more lasting impression for yourself if you allow yourself the frustration and eventual joy of doing it yourself than you would by reading the code written by a generative AI-powered assistant.

Each time you are asked to provide code, there will be a *test* for your code below the relevant code cell.
Usually, there will be a comment in that cell with the desired output.
If your output matches that comment, you know that your code at least works in that instance!
Sometimes no desired output is provided. In that case, it is because there are theoretical methods to anticipate what the output should be from lecture or the textbook.
If you don't know what the test should output, discuss with a classmate or your TA!
Whether a test is provided or not, you are very much encouraged to write your own!

To try out getting help, in the code cell below, use the `help` function to bring up help on the Python built-in `max` function.



In [ ]:
help(max)

##  Python: variables, numbers, objects, types, strings, lists
This is intended as a very quick introduction.
You are encouraged to seek out more resources to gain more familiarity and comfort with the language.
For example, [this](https://www.w3schools.com/python/python_intro.asp) is a free tutorial which goes in significantly more depth.

### Variables, Numbers, and Booleans

One of the most basic features of the python language are *variables*.
These are names which in general reference *data types*.
We'll see examples of more complex types later, but let's start with some simple ones, such as numerical types.
The following example makes use of the `print` function, which as you'll see provides information about its argument to output.
**To evaluate a jupyter cell, hit shift-enter after selecting that cell.**

In [1]:
a=9
b=3
print(a+b) # addition
print(a*b) # multiplication
print(a-b) # subtraction


12
27
6


Much of Python's syntax is quite intuitive, but there are a few quirks to get used to.

In [2]:
print(a^b) # surprise! was that what you expected?
print(a**b) # what do these last two do?

10
729


As you've now seen, exponentiation was handled differently than you may have expected.
`^` is reserved for *bitwise xor*, while **exponentiation is represented with `**`.**
<details>
    <summary>
        <b>
            More on ^
        </b>
        (Click to expand)
    </summary>

We won't be using `^` during the course of these activities (at least unless you happen to find creative ways of doing so). We can, however, briefly explain what it does. On bits (i.e. 1 or 0), `a^b` returns `1` if exactly one of `a` and `b` is equal to `1` and 0 if both are 0 or both are 1.
On strings of bits (e.g. `1001` or `0011`), bitwise xor acts by applying to each bit one-by-one.
So in this example, we would see that `(1001)^(0011)` is `1010`.

Of course, as you may know, computers represent numbers as binary strings. $9=1*2^3+0*2^2+0*2^1+2^0$, so we would represent 9 as `1001`, and $3=0*2^3+0*2^2+1*2^1+2^0$, so we would represent 3 as `0011`. Then, the result of `9^3` above is `1010`, which we read as $1*2^3+0*2^2+1*2^1+0*2^0=10$. Indeed, that's what we got when we tried it!
</details>
One other subtlety comes about in division.
Try out the following example.

In [3]:
print(a//b) # what is this?
print(a/b)  # how about this?

3
3.0


Those were the same, but now **you try!** With $a=8$ and $b=3$, what do you get for `a/b` and `a//b`?

In [4]:
#YOUR CODE HERE
a=8
b=3
print(a/b)
print(a//b)

2.6666666666666665
2


Every object in Python has a *type*.
You can check types using the `type` function.
For example, try checking the type of `a` and `a/b` below.

In [5]:
type(a)

int

In [6]:
type(a/b)

float

Note they are different!
The `int` type is used to represent whole numbers, while the `float` type is used to represent decimals.
In our applications, we will be primarily working with `float`s.
For the most part, we'll be able to sidestep these subtleties, but there will be cases in which some care will be necessary.

### Booleans and Comparisons
Another highly fundamental type is that of the boolean, implemented in Python as the `bool` type.
There are two tokens belonging to the type: `True` and `False`.
There are some very common functions of booleans which are built-in to Python: `and` and `or`, and the operator `not`.

In [7]:
A=False
B=True
print(A and B)
print(A or B)
print(not B)
print((not A) and B)

False
True
False
True


One place where `bool`s very frequently come up is comparison:
- `==` checks for equality
- `>` and `<` check for greater and less than respectively
- `>=` and `<=` check for greater than or equal to and less than or equal to respectively.

In [8]:
#what do you expect this to print?
a=5
b=6
c=5/6
print(a>b)
print(a<b)
print(a/b > c)
print(a/b >=c)
print(a/b==c)


False
True
False
True
True


### Strings and Lists

Another object which will come up for us are `string`s.
These are a mode of storing text.
Take a look at the example below.


In [9]:
a= "Hello"
b= " "
c= "World"
d= "!"
print(a+b+c+d)
print(a*15)

Hello World!
HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello


**You try!** Try to come up with a way to print "Hello!!!" 20 times, with a space in between each instance.

In [10]:
#YOUR CODE HERE
print((a+b)*20)

Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello 


Strings behave similarly to another important data type, that of the `list`.
To form a `list`, simply put a sequence of values, separated by commas, into square brackets `[]`.
For example, here is a list of some strings.

In [11]:
A=[a+b+c+d,
   a+2*b+3*c+4*d,
   d+2*c+3*b+4*a,
   a+d+c+d+a+d,
   5*(a+d+b),
   3*(c+d+b)]
A

['Hello World!',
 'Hello  WorldWorldWorld!!!!',
 '!WorldWorld   HelloHelloHelloHello',
 'Hello!World!Hello!',
 'Hello! Hello! Hello! Hello! Hello! ',
 'World! World! World! ']

`len` gives the length of a list.

In [12]:
len(A)

6

Lists are *indexed* with square brackets as well.
This is, in essence, a means of calling elements of a list or a range within.
Here's an example using the previous list:

In [13]:
print(A[0])     #lists are always indexed starting at 0
print(A[5])     #our list has six elements, so 5 is the last one (since we started at 0)
print(A[-1])    #negative indexing starts at the end with -1 (so this is the same as A[5])
print(A[1:3])   #gives list items 1 and 2 (in general, it includes the part before the colon, but not the part after)
print(A[2:])    #start at item 2 (inclusive) until the end
print(A[:3])    #start at the beginning and end at item 3 (exclusive)

Hello World!
World! World! World! 
World! World! World! 
['Hello  WorldWorldWorld!!!!', '!WorldWorld   HelloHelloHelloHello']
['!WorldWorld   HelloHelloHelloHello', 'Hello!World!Hello!', 'Hello! Hello! Hello! Hello! Hello! ', 'World! World! World! ']
['Hello World!', 'Hello  WorldWorldWorld!!!!', '!WorldWorld   HelloHelloHelloHello']


**You try!** print the list that starts at the beginning and ends after item 3 (`'Hello!World!Hello!'`). Then, print the list that starts at item 4 and goes until the end.

In [14]:
#YOUR CODE HERE
print(A[1:4])
print(A[4:])

['Hello  WorldWorldWorld!!!!', '!WorldWorld   HelloHelloHelloHello', 'Hello!World!Hello!']
['Hello! Hello! Hello! Hello! Hello! ', 'World! World! World! ']


The same indexing works on strings:

In [15]:
f=5*(a+b+c+d)
print(f[6:25])
print(f[6:25:2]) #The third digit tells us to increment by that many as we go from item to item
print(f[24:5:-1]) #it accepts negative arguments


World!Hello World!H
WrdHloWrdH
H!dlroW olleH!dlroW


Now **you try!** How would you print starting six characters from the end and ending on the sixth character, incrementing backwards and skipping every other letter?

In [16]:
#YOUR CODE HERE
print(f[:6:-6])
#desired output:(they are all the '!')
#WolHdrWolHdrWolHdrWolHdrW

! ! ! ! !


We'll be revisiting lists in greater detail soon once we start working with NumPy!
## Control Sequences: Conditionals, Loops, Iteration, and Functions
### If and Else

Control sequences let us structure our code into blocks and provide a logical flow to our programs.
Perhaps the most basic of these is the conditionals `if` and `else`.
The basic syntax for these is:
```python
if x:
    y
else:
    z
```
Here, `x` is a `bool` and `y` and `z` are ensuing code (which can be multi-line).
Note the spacing.
**Any control block starts with a line ending with a colon.
Any subsequent code within the control block then must have a tab at the beginning of the line.**
As an example, play around with the following by changing the value of `num` in the first line.

In [17]:
num = 3
if num % 2 ==0:       #the % symbol is the remainder-- i.e. if num has a remainder of 0 after being divided by 2
    print("even")
else:
    print("odd")

odd


** You try!** Rework the example below to write code which prints `num/2` if `num` is even, `(num-1)/2` if `num` is odd and negative, and `(num+1)/2` if `num` is odd and positive.
(You can do this by nesting `if` and `else` statements, or using the `elif` control sequence).

In [20]:
#YOUR CODE HERE
num = -5 # You can change this number to test different cases
if num % 2 == 0:
    print(num/2)
elif num < 0:
    print((num-1)/2)
else:
    print((num+1)/2)

-3.0


### Loops
Often, we'll want to automate repetitive tasks.
Python supplies *loops* for this purpose.
For instance, suppose I have a recursive function given by the formula $a_n=(1-2a_{n-1})/3$ and wanted to know what $a_10$ would be if I started with $a_0=1$.
The following loop does just that:

In [21]:
a=1
for n in range(10):   #This says I am letting n=0, performing the code below it, then letting n=1, then n=2, etc. through n=9.
    #It is exclusive of the argument (so range(10) is 0,1,2,...,9, *not* including 10).
    #Notice the colon at the end! You will get an error without one!
    #each new line in the loop must start with a tab
    print("a_",n,"=",a) #check in on current value--think through why the indexing makes sense!
    a=(1-2*a)/3         #find a_n from a_{n-1}
a   #this is outside of the loop because it doesn't start with a tab


a_ 0 = 1
a_ 1 = -0.3333333333333333
a_ 2 = 0.5555555555555555
a_ 3 = -0.03703703703703698
a_ 4 = 0.35802469135802467
a_ 5 = 0.09465020576131689
a_ 6 = 0.27023319615912206
a_ 7 = 0.15317786922725196
a_ 8 = 0.23121475384849868
a_ 9 = 0.1791901641010009


0.21387322393266608

Note that in the line `a=(1-2*a)/3`, we referenced the value of the variable we were changing!

#### Exercise 1: Looping to Compute Recursive Sequences
**Exercise: (a):** Alter the above to compute the 15th term of the recursive sequence $b_n=(1+2b_{n-1})/4$ starting with $b_0=2$.
To check that your code is working as intended, here's the first few terms:
```
b_ 0 = 2
b_ 1 = 1.25
b_ 2 = 0.875
b_ 3 = 0.6875
```


In [22]:
#YOUR CODE HERE
b=2
for n in range(15):
    print("b_",n,"=",b)
    b=(1+2*b)/4


b_ 0 = 2
b_ 1 = 1.25
b_ 2 = 0.875
b_ 3 = 0.6875
b_ 4 = 0.59375
b_ 5 = 0.546875
b_ 6 = 0.5234375
b_ 7 = 0.51171875
b_ 8 = 0.505859375
b_ 9 = 0.5029296875
b_ 10 = 0.50146484375
b_ 11 = 0.500732421875
b_ 12 = 0.5003662109375
b_ 13 = 0.50018310546875
b_ 14 = 0.500091552734375


___

**(b)** Consider the *two-variable* recursion given by $c_n=\frac{(c_{n-1}+d_{n-1})}{2c_{n-1}d_{n-1}}$ , $d_n=\frac{c_{n-1}^2}{c_{n-1}+d_{n-1}}$. Find $c_{20}$ and $d_{20}$ when $c_0=d_0=1$. Like before, print out $c_n$ and $d_n$ for each $n$.

To check your sequence is working, here are the first few terms:
```
c_ 0 = 1 ; d_ 0 = 1
c_ 1 = 1.0 ; d_ 1 = 0.5
c_ 2 = 1.5 ; d_ 2 = 0.6666666666666666
c_ 3 = 1.0833333333333333 ; d_ 3 = 1.0384615384615385
```

<details>
    <summary> <b> Hint:</b> (click here to open)</summary>

- if you copy the method of the above exactly, you may find yourself overwriting variables you need to store. Introducing a new variable (say, "`a_last`") is one way out of that pickle.    
</details>

In [28]:
#YOUR CODE HERE
c = d = 1
for n in range (20):
    print("c_",n,"=",c)
    print("d_",n,"=",d)
    c = (c+d) / (2*c * d)
    d = (c**2) / (c + d)



c_ 0 = 1
d_ 0 = 1
c_ 1 = 1.0
d_ 1 = 0.5
c_ 2 = 1.5
d_ 2 = 1.125
c_ 3 = 0.7777777777777778
d_ 3 = 0.31792376317923765
c_ 4 = 2.2155612244897958
d_ 4 = 1.9375333042644347
c_ 5 = 0.4837365339131978
d_ 5 = 0.0966439306155464
c_ 6 = 6.207251137792241
d_ 6 = 6.112088838647947
c_ 7 = 0.16235604753609828
d_ 7 = 0.004201086574142332
c_ 8 = 122.09647964740955
d_ 8 = 122.0922787053811
c_ 9 = 0.008190385233469433
d_ 9 = 5.494033788097093e-07
c_ 10 = 910139.1779124964
d_ 10 = 910139.177911947
c_ 11 = 1.0987330556343164e-06
d_ 11 = 1.3264062869062192e-18
c_ 12 = 3.769584062865311e+17
d_ 12 = 3.769584062865311e+17
c_ 13 = 2.6528125738092355e-18
d_ 13 = 1.8668941810018025e-53
c_ 14 = 2.67824499689475e+52
d_ 14 = 2.67824499689475e+52
c_ 15 = 3.7337883620036055e-53
d_ 15 = 5.205339895490311e-158


OverflowError: (34, 'Numerical result out of range')

___

### Functions

Sometimes, we'll want to perform the same process to a variety of different inputs.
As a first example, one classic example is the factorial $n!$.
Below is a somewhat nonstandard implementation of the factorial--in a moment, we'll explain why we say this is nonstandard.

In [30]:
def my_factorial(n):
    #
    #once again, the colon is necessary and everything within the function will start with a tab
    prod=1                  #initialize
    for k in range(1,n+1):  #This syntax means start at 1 and stop at n+1, excluding n+1 (so k=1,2,...,n)
        print(k)            #strictly unnecessary, for illustrative purposes
        prod=prod*(k)
    return prod

In [31]:
my_factorial(0) #check this works correctly for n=0

1

In [32]:
my_factorial(5)

1
2
3
4
5


120

**Your turn** find 8! with `my_factorial`.

In [33]:
#YOUR CODE HERE
my_factorial(8)

1
2
3
4
5
6
7
8


40320

Functions can take more than just one argument as input.
For instance, we can alter our code from the example above to compute $a_N$ for any $N$ and any value for $a_0$, rather than just $N=10$ and $a_0=1$.

In [34]:
def a_N(N,a_0):  #This says our function takes two arguments, N and a_0
    a=a_0         #generalizing from above--a is the variable we'll work with, a_0 is supplied by argument
    for n in range(N): # generalizing from above
        #now, we need two tabs to place code in the loop.
        print("a_",n,"=",a)
        a=(1-2*a)/3
    return a      #every function has to end with a return line
a_N(20,3)  #This finds a_20 with a_0=3.
           #the value at the bottom is what is computed in the line starting with "return"


a_ 0 = 3
a_ 1 = -1.6666666666666667
a_ 2 = 1.4444444444444446
a_ 3 = -0.6296296296296298
a_ 4 = 0.7530864197530865
a_ 5 = -0.16872427983539104
a_ 6 = 0.4458161865569274
a_ 7 = 0.036122542295381734
a_ 8 = 0.3092516384697455
a_ 9 = 0.12716557435350298
a_ 10 = 0.24855628376433136
a_ 11 = 0.16762914415711241
a_ 12 = 0.22158057056192507
a_ 13 = 0.18561295295871663
a_ 14 = 0.20959136469418893
a_ 15 = 0.1936057568705407
a_ 16 = 0.20426282875297286
a_ 17 = 0.19715811416468476
a_ 18 = 0.20189459055687684
a_ 19 = 0.19873693962874875


0.20084204024750085

#### Exercise 2(a): Functions of your own!
**(a)** Similar to above, return to your code from exercise 1(a) and generalize it to a function `b_N` which take arguments `N` and `b_0` and returns the `N`th term of the recursive sequence defined by $b_n=(1+2b_{n-1})/4$ where $b_0$ is given by the argument `b_0`.
Once again, your function should print the current value of $b_n$ at each $n$.
To make sure your function is correct, you are given that when $b_0=10000$, $b_{23}=0.501192033290863$.

In [37]:
#YOUR CODE HERE
def b_N(N,b_0):   #You need to fill in the argument yourself
    b=b_0
    for n in range(N):
        print("b_",n,"=",b)
        b=(1+2*b)/4
    return b
b_N(23,10000)

b_ 0 = 10000
b_ 1 = 5000.25
b_ 2 = 2500.375
b_ 3 = 1250.4375
b_ 4 = 625.46875
b_ 5 = 312.984375
b_ 6 = 156.7421875
b_ 7 = 78.62109375
b_ 8 = 39.560546875
b_ 9 = 20.0302734375
b_ 10 = 10.26513671875
b_ 11 = 5.382568359375
b_ 12 = 2.9412841796875
b_ 13 = 1.72064208984375
b_ 14 = 1.110321044921875
b_ 15 = 0.8051605224609375
b_ 16 = 0.6525802612304688
b_ 17 = 0.5762901306152344
b_ 18 = 0.5381450653076172
b_ 19 = 0.5190725326538086
b_ 20 = 0.5095362663269043
b_ 21 = 0.5047681331634521
b_ 22 = 0.5023840665817261


0.501192033290863

___

We can write a function which performs the same using *recursion*.
This is a function which calls itself to compute.
This is best illustrated with a classic example.
Recall that the factorial $n!$ is defined as $n*(n-1)*\dots *2*1$ with the convention that $0!=1$.
Equivalently, $n!$ can be defined as $n*(n-1)!$ along with the declaration $0!=1$.
The following uses this latter definition to define the factorial in Python.
This is the much more commonly seen method of defining the factorial.

*Note:* The `print` statements are for illustrative purposes only.
How does the printed output of `my_factorial` differ from that of `my_factorial_recursive`?
Why do you think that is?

In [38]:
def my_factorial_recursive(n):
    if n==0:
        print(n)
        return 1
    else:
        print(n)
        return n*my_factorial_recursive(n-1)


In [39]:
my_factorial_recursive(15)

15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0


1307674368000

In [40]:
my_factorial(15)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


1307674368000

We can also give a recursive definition of `a_N`.

In [42]:
def recursive_a_N(N,a_0):
    if N==0:
        a=a_0
        print("a_",N,"=", a)
        return a
    else:
        #print("a_",N-1,"=", recursive_a_N(N-1,a_0)) #what do you think will happen if we un-comment this?
        a=(1-2*recursive_a_N(N-1,a_0))/3
        print("a_",N,"=", a)
        return a

In [43]:
recursive_a_N(15,1)

a_ 0 = 1
a_ 1 = -0.3333333333333333
a_ 2 = 0.5555555555555555
a_ 3 = -0.03703703703703698
a_ 4 = 0.35802469135802467
a_ 5 = 0.09465020576131689
a_ 6 = 0.27023319615912206
a_ 7 = 0.15317786922725196
a_ 8 = 0.23121475384849868
a_ 9 = 0.1791901641010009
a_ 10 = 0.21387322393266608
a_ 11 = 0.1907511840448893
a_ 12 = 0.2061658773034071
a_ 13 = 0.19588941513106195
a_ 14 = 0.20274038991262536
a_ 15 = 0.1981730733915831


0.1981730733915831

In [44]:
a_N(15,1)  #check this was what we were expecting

a_ 0 = 1
a_ 1 = -0.3333333333333333
a_ 2 = 0.5555555555555555
a_ 3 = -0.03703703703703698
a_ 4 = 0.35802469135802467
a_ 5 = 0.09465020576131689
a_ 6 = 0.27023319615912206
a_ 7 = 0.15317786922725196
a_ 8 = 0.23121475384849868
a_ 9 = 0.1791901641010009
a_ 10 = 0.21387322393266608
a_ 11 = 0.1907511840448893
a_ 12 = 0.2061658773034071
a_ 13 = 0.19588941513106195
a_ 14 = 0.20274038991262536


0.1981730733915831

#### Exercise 2(b): Recursive Functions for Recursive Sequences
Below, give a recursive version of `b_N`.
You no longer need include any `print` statements.
Be sure to check your `recursive_b_N` against the original `b_N` to make sure they give the same values.

In [47]:
#YOUR CODE HERE
def recursive_b_N(N,b_0):
  if N == 0:
      b = b_0
      print("b_",N,"=", b)
      return b
  else:
    b = (1+2*recursive_b_N(N-1,b_0))/4
    print("b_",N,"=", b)
    return b
print(recursive_b_N(23,10000))

b_ 0 = 10000
b_ 1 = 5000.25
b_ 2 = 2500.375
b_ 3 = 1250.4375
b_ 4 = 625.46875
b_ 5 = 312.984375
b_ 6 = 156.7421875
b_ 7 = 78.62109375
b_ 8 = 39.560546875
b_ 9 = 20.0302734375
b_ 10 = 10.26513671875
b_ 11 = 5.382568359375
b_ 12 = 2.9412841796875
b_ 13 = 1.72064208984375
b_ 14 = 1.110321044921875
b_ 15 = 0.8051605224609375
b_ 16 = 0.6525802612304688
b_ 17 = 0.5762901306152344
b_ 18 = 0.5381450653076172
b_ 19 = 0.5190725326538086
b_ 20 = 0.5095362663269043
b_ 21 = 0.5047681331634521
b_ 22 = 0.5023840665817261
b_ 23 = 0.501192033290863
0.501192033290863


### Defaults, List Arguments, and Optional Arguments
One common technique in defining functions is to assign default values to arguments.
This is perhaps best illustrated by example.

In [48]:
def print_if_you_like(String="no input provided"):
    print(String)
    return

In [49]:
print_if_you_like("here is a string provided by the user")

here is a string provided by the user


In [50]:
print_if_you_like(String="here's another way to call this function")

here's another way to call this function


In [51]:
print_if_you_like()  #what do you expect the output to be?

no input provided


Often, we'll need functions that take an unknown number of inputs.
There are two major ways of doing this: optional arguments and list arguments.
To demonstrate list arguments, here is a function which takes a list of numbers and adds them all up.
Note how the loop is set up!

In [52]:
def list_sum(numlist=[]): #default to empty list
    tot=0                 #sum of nothing is 0
    for n in numlist:     #no need to call len(numlist)!
        tot+=n            #same as tot=tot+n
    return tot


In [53]:
list_sum([1,2,-3,4])

4

In [54]:
list_sum()

0

Here is an essentially identical function using optional arguments instead.
Think of the asterisk `*` as declaring that there may be any number of arguments, which the function treats as a list called `numlist`.

In [55]:
def optional_sum(*numlist):
    tot=0
    for n in numlist:
        tot+=n
    return tot

In [56]:
optional_sum()

0

In [57]:
optional_sum(1,2,-3,4)     #note the arguments are not enclosed in a list this time!

4

The following will throw an error. Uncomment the code line by removing the `#` at the beginning and see what the error says. Why do you think it occurred?

In [58]:
optional_sum([1,2,-3,4])   #this doesn't work
# it may because the [] cause the type changed, which defined in another function

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

#### Exercise 2(c) Optional and List Arguments of Your Own.
(i)Write functions `list_mult` and `optional_mult` which behave similarly to `list_sum` and `optional_sum` but instead multiply their arguments.

(ii)Then, write a function `arg_reader` which prints each of its arguments (say `arg`) and the number `n` of remaining terms in the format "reading `arg`, `n` arguments remain" then prints "all done!".
You may use either a list argument or optional arguments.

<details>
<summary>
    <b>
        Details for (ii)
    </b> (Click here to open)
</summary>
    
Example input (list version):
```python
arg_reader(["Nebraska","Wisconsin", 1/3,11/4,311/25])
```
Example input (optional argument version)
```python
arg_reader("Nebraska","Wisconsin", 1/3,11/4,311/25)
```
Output (both):
```
reading Nebraska . 4 arguments remain
reading Wisconsin . 3 arguments remain
reading 0.3333333333333333 . 2 arguments remain
reading 2.75 . 1 arguments remain
reading 12.44 . 0 arguments remain
all done!
```

    
</details>


<details>
    <summary>
        <b> Hint: </b>
        (click here to open)
    </summary>

- To print more complicated statements like this, `print` takes optional arguments!
  For example:
```python
a=1
b=2
c="red"
d="blue"
print(a,"fish",b,"fish",c,"fish",d,"fish")
```
returns
```
1 fish 2 fish red fish blue fish
```

</details>

In [97]:
#YOUR CODE HERE
def list_mult(numlist=[]):
    tot=1
    for n in numlist:
        tot*=n
    return tot
def optional_mult(*numlist):
    tot=0
    for n in numlist:
        tot*=n
    return tot
def arg_reader(*args):
    for i, arg in enumerate(args):
        print("reading", arg, ". ", len(args)-i-1, "arguments remain")
    print("all done!")
    return
arg_reader("Nebraska","Wisconsin", 1/3,11/4,311/25)

reading Nebraska .  4 arguments remain
reading Wisconsin .  3 arguments remain
reading 0.3333333333333333 .  2 arguments remain
reading 2.75 .  1 arguments remain
reading 12.44 .  0 arguments remain
all done!


___

## Introducing NumPy
The very first thing to do with any library we utilize is to *import* it into the current project:

In [2]:
import numpy as np

This allows us to use the library's functions and objects.
To see a list of these, type `np.` into a cell and hit the "Tab" key--this will bring up the sublibraries and functions available.

### The `np.ndarray`
The basic object offered by `numpy` is the `ndarray` data type.
One can instantiate an `ndarray` with the `np.array` function, as below.
`np.array` takes a list as input.
For a multidimensional array (such as a matrix), we use a list of lists, with each inner list representing a row.

In certain applications, `ndarray`s with `int` entries can have unexpected behavior.
To prevent this, we'll explicitly *declare* the type as `float64` when calling `np.array`--you are encouraged to get in the habit of including the `"float64"` at the end, as below.

In [32]:
A=np.array([[1,2],[3,4],[5,6]],"float64")
type(A)

numpy.ndarray

You can check the number of dimensions of an `ndarray` with the `ndim` method:

In [33]:
A.ndim

2

Every `ndarray` has a `shape`, giving its dimensions.

In [34]:
A.shape #what do you expect it to be?

(3, 2)

Since `A` is a two-dimensional array with two rows and two columns, it has shape `(2,2)`.
**Throughout these activities, we will be using the term "matrix" as a synonym for 2-dimensional `ndarray`.**

In [36]:
v=np.array([1,-3],"float64")
v.ndim

1

In [37]:
v.shape

(2,)

One can also use syntax similar to that of for loops to construct `ndarray`s.
This will be a crucial tool for us.

In [65]:
w=np.array([k**2 for k in range(5)],"float64")
w

array([ 0.,  1.,  4.,  9., 16.])

In [66]:
B=np.array([[i-j/2 for j in range(5)] for i in range(2)],"float64")
B

array([[ 0. , -0.5, -1. , -1.5, -2. ],
       [ 1. ,  0.5,  0. , -0.5, -1. ]])

Indexing is similar to before, but now we can supply multiple index arguments.

In [67]:
B[1] #the 1-indexed row

array([ 1. ,  0.5,  0. , -0.5, -1. ])

In [68]:
print(B[1][2]) #the 2-indexed entry of the 1-indexed row\
print(B[1,2]) #this is exactly the same

0.0
0.0


A crucial technique for working with `ndarray`s is *slicing*.
This allows us to take submatrices.
For instance, suppose we want to extract the middle column of `B`:

In [69]:
c=B[:,2]  #colon in first entry means ranging from beginning to end, 2 in second entry specifies column
c

array([-1.,  0.])

In [70]:
c.shape #notice that numpy automatically stores it in as few dimensions as possible

(2,)

Beyond extracting columns, one can extract larger submatrices.

In [71]:
B[:,1:] # all columns starting with column 1

array([[-0.5, -1. , -1.5, -2. ],
       [ 0.5,  0. , -0.5, -1. ]])

#### Exercise 3: Constructing and Slicing Matrices
**(a)** In the cell below, construct a $5\times 6$ matrix $C=(\frac{i+1}{j+1})_{ij}$.
That is, your code should produce the matrix $$
\begin{pmatrix}
1 & \frac{2}{3} & \frac{1}{2} & \frac25 &\frac13 & \frac27\\
\frac32 & 1 & \frac{3}{4} & \frac35&\frac12 & \frac37\\
2 & \frac{4}{3} & 1 & \frac45 &\frac23 & \frac47\\
\frac52 & \frac{5}{3} & \frac{5}{4} & 1 &\frac56 & \frac57\\
3 &2 & \frac{3}{2} & \frac65 &1 & \frac67
\end{pmatrix}.$$

Be sure to account for Python indexing conventions! (i.e. starting at 0). You may need to adjust your formula to do so.


In [24]:
#YOUR CODE HERE
# a = np.array ([[(i+1)/(j+1) for i in range(6)] for j in range(5)],"float64")
a=[]
for i in range(5):
  b=[]
  for j in range(6):
      b.append((i+2)/(j+2))
  a.append(b)
a = np.array(a)
print(a)


[[1.         0.66666667 0.5        0.4        0.33333333 0.28571429]
 [1.5        1.         0.75       0.6        0.5        0.42857143]
 [2.         1.33333333 1.         0.8        0.66666667 0.57142857]
 [2.5        1.66666667 1.25       1.         0.83333333 0.71428571]
 [3.         2.         1.5        1.2        1.         0.85714286]]


___

**(b):** Use *slicing* to extract the third row (that is $\begin{pmatrix}2&\frac43&1&\frac45&\frac23&\frac47\end{pmatrix}$) and the fourth column (that is $\begin{pmatrix}\frac25&\frac35&\frac45&1&\frac65\end{pmatrix}$) as vectors `u_1` and `u_2` respectively. Do **not** use any other method to do so.

In [25]:
#YOUR CODE HERE
u_1 = a[2]
u_2 = a[:,3]
print(u_1)
print(u_2)

[2.         1.33333333 1.         0.8        0.66666667 0.57142857]
[0.4 0.6 0.8 1.  1.2]


___

**(c):** Use slicing to extract the submatrix `C_abridged` which only has the second through fourth rows and third and fourth column.
That is, your code should produce the matrix
$$
\begin{pmatrix}
 \frac{3}{4} & \frac35\\%&\frac12 & \frac37\\
1 & \frac45\\% &\frac23  \frac47\\
 \frac{5}{4} & 1% &\frac56 & \frac57\\
\end{pmatrix}
$$

In [26]:
#YOUR CODE HERE
C_abridged = a[1:4,2:4]
C_abridged

array([[0.75, 0.6 ],
       [1.  , 0.8 ],
       [1.25, 1.  ]])

___

**(d)** [View vs. Copy]

- (i) Change the 3/4 in the second row of `C` to 99. Does that change `C_abridged`?
- (ii) Change the 1 in the second row of `C_abridged` to -99. Does that change `C`?
- (iii) Enter in the line `C_new=C.copy()`, then change the second row of `C_new` to five times the first. Does that change `C`?
- (iv) Summarize your findings below.

In [28]:
#(i)
#YOUR CODE HERE
C = a
C[1][0] = 99
print(C_abridged)

[[0.75 0.6 ]
 [1.   0.8 ]
 [1.25 1.  ]]


In [29]:
#(ii)
#YOUR CODE HERE
C_abridged[1][0] = -99
print(C)

[[  1.           0.66666667   0.5          0.4          0.33333333
    0.28571429]
 [-99.           1.           0.75         0.6          0.5
    0.42857143]
 [  2.           1.33333333 -99.           0.8          0.66666667
    0.57142857]
 [  2.5          1.66666667   1.25         1.           0.83333333
    0.71428571]
 [  3.           2.           1.5          1.2          1.
    0.85714286]]


In [78]:
#(iii)
#YOUR CODE HERE
C_new = C.copy()
C_new[1] = 5*C_new[0]
print(C)


[[  1.           0.5          0.33333333   0.25         0.2
    0.16666667]
 [ 99.           1.5          1.33333333   1.25         1.2
    1.16666667]
 [  3.           2.5        -99.           2.25         2.2
    2.16666667]
 [  4.           3.5          3.33333333   3.25         3.2
    3.16666667]
 [  5.           4.5          4.33333333   4.25         4.2
    4.16666667]]


(This is an empty markdown cell to write your answer to (iv))


Finding: Each procedure change as code shows.

___

Matrix multiplication is implemented with `np.dot` for compatibly sized arrays.

In [30]:
M=np.array([[((-2/3)**i)+(3/5)**j for j in range(5)] for i in range(2)],"float64")
N=np.array([[(-3/2)**i*(4/7)**j for j in range(3)] for i in range(5)],"float64")
print(M.shape,N.shape)
MN=np.dot(M,N)
print(MN)
print(MN.shape)

(2, 5) (5, 3)
[[ 4.2746      2.44262857  1.39578776]
 [-1.45456667 -0.83118095 -0.47496054]]
(2, 3)


This works even mixing dimensions.

In [38]:
print(A.shape,v.shape)

(3, 2) (2,)


In [81]:
Av=np.dot(A,v)
Av.shape,Av

((3,), array([ -5.,  -9., -13.]))

#### Exercise 4: Please just trust me on this, you'll be glad you did this one
Use optional arguments to write a function which takes one or more matrices of compatible definitions $A_1,A_2,\dots,A_n$ and returns the matrix product $A_1A_2\dots A_n$.

<details>
<summary>
<b>
    Hint:
</b>
    (Click here to open)
</summary>
    
-    Note that unlike our sums and products of before, this suggests taking one or more input matrices rather than zero or before. Why might that be? In any case, you can have both required and optional arguments in the form (say) `def mult(A,*Bs):`
    
</details>

In [39]:
from typing import ByteString
#YOUR CODE HERE
def mult(A, *Bs):
    result = A
    for B in Bs:
      result = np.dot(result, B)
    return result

In [40]:
#testing
v_1=np.array([2**i for i in range(4)],"float64")
A_1=np.array([[i+j for j in range(5)]  for i in range(4)],"float64")
A_2=np.array([[1/(i+j+1) for j in range(5)] for i in range(5)],"float64")
A_3=np.array([[i-j for j in range(6)] for i in range(5)],"float64")
v_2=np.array([1/2**i for i in range(6)],"float64")
mult(v_1,A_1,A_2,A_3,v_2)
#desired output:
#425.32607886904765

np.float64(425.32607886904754)